#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect requirements
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo su
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
