#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect requirements
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
