#!/usr/bin/env bash
# redirection
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
to_add='location /redirectme {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}'
sudo sed -i "/server_name _;/a $to_add" /etc/nginx/sites-available/default
if sudo nginx -t; then
	sudo service nginx restart
else
	echo 'try'
fi
