#!/usr/bin/env bash
# redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
to_add="\tlocation /redirec_tme {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "/server_name _;/a \\$to_add" /etc/nginx/sites-available/default
sudo service nginx restart
