#!/usr/bin/env bash
# custom error page
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_error > /dev/null
string="\terror_page 404 /custom_error;"
sudo sed -i "/server_name _;/a \\$string" /etc/nginx/sites-available/default
sudo service nginx restart
