#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
header="\tadd_header X-Served-By $HOSTNAME"
sudo sed -i "/server_name _;/a \\$header;" /etc/nginx/sites-available/default
sudo service nginx restart
